# Generated by Django 5.2.6 on 2025-09-17 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etlrun',
            options={'managed': True, 'ordering': ['-started_at']},
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='message',
            field=models.TextField(db_collation='Modern_Spanish_CI_AS'),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='process',
            field=models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=120),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='rows_affected',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='started_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='status',
            field=models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios'),
        ),
        migrations.AddIndex(
            model_name='etlrun',
            index=models.Index(fields=['started_at'], name='etl_runs_started_41a31e_idx'),
        ),
        migrations.AddIndex(
            model_name='etlrun',
            index=models.Index(fields=['status'], name='etl_runs_status_1f650e_idx'),
        ),
    ]
