# Generated by Django 5.2.6 on 2025-09-17 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuarios_table'),
        ('etl', '0002_alter_etlrun_options_alter_etlrun_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etlrun',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios'),
        ),
    ]
