# Generated by Django 5.2.6 on 2025-09-17 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_alter_etlrun_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etlrun',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='etlrun',
            name='etl_runs_started_41a31e_idx',
        ),
        migrations.RemoveIndex(
            model_name='etlrun',
            name='etl_runs_status_1f650e_idx',
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='process',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='rows_affected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='status',
            field=models.CharField(default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
