# Generated by Django 5.2.6 on 2025-09-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraVentas',
            fields=[
                ('id_bitacora', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_venta', models.IntegerField()),
                ('operacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('datos_anteriores', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('datos_nuevos', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('usuario_evento', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('fecha_evento', models.DateTimeField()),
            ],
            options={
                'db_table': 'dbo.bitacora_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaGastos',
            fields=[
                ('id_categoria_gastos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'dbo.categoria_gastos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProductos',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'dbo.categoria_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('apellido_cliente', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'dbo.clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuotaCreditos',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuota', models.IntegerField()),
                ('monto_programado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'dbo.cuota_creditos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'dbo.detalle_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimFecha',
            fields=[
                ('id_fecha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('trimestre', models.IntegerField()),
                ('semana_iso', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('nombre_mes', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
                ('nombre_dia', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
                ('es_fin_de_mes', models.BooleanField()),
            ],
            options={
                'db_table': 'dbo.dim_fecha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_gasto', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('monto_gasto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'dbo.gastos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'dbo.pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'dbo.permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'dbo.productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'dbo.roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StgDetalleVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo_venta', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('producto', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('categoria_producto', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'dbo.stg_detalle_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StgGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('categoria_gasto', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('nombre_gasto', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('monto_gasto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'dbo.stg_gastos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StgVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo_venta', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('cliente_nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('cliente_apellido', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('tipo_cliente', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('tipo_transaccion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('plazo_mes', models.IntegerField(blank=True, null=True)),
                ('interes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_venta_final', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'dbo.stg_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoClientes',
            fields=[
                ('id_tipo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_cliente', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100, unique=True)),
                ('tasa_interes_default', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'dbo.tipo_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTransacciones',
            fields=[
                ('id_tipo_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_transaccion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'dbo.tipo_transacciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50, unique=True)),
                ('password_hash', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('nombre_completo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'dbo.usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('plazo_mes', models.IntegerField()),
                ('interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_venta_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'dbo.ventas',
                'managed': False,
            },
        ),
    ]
