# Generated by Django 5.2.6 on 2025-09-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
