# Generated by Django 5.2.6 on 2025-09-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuarios_table'),
        ('etl', '0004_alter_etlrun_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id_tipo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_cliente', models.CharField(max_length=100, unique=True)),
                ('tasa_interes_default', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Tipo de cliente',
                'verbose_name_plural': 'Tipos de cliente',
                'db_table': 'tipo_clientes',
            },
        ),
        migrations.DeleteModel(
            name='BitacoraVentas',
        ),
        migrations.DeleteModel(
            name='CategoriaGastos',
        ),
        migrations.DeleteModel(
            name='CategoriaProductos',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='CuotaCreditos',
        ),
        migrations.DeleteModel(
            name='DetalleVentas',
        ),
        migrations.DeleteModel(
            name='DimFecha',
        ),
        migrations.DeleteModel(
            name='Gastos',
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='StgDetalleVentas',
        ),
        migrations.DeleteModel(
            name='StgGastos',
        ),
        migrations.DeleteModel(
            name='StgVentas',
        ),
        migrations.DeleteModel(
            name='TipoClientes',
        ),
        migrations.DeleteModel(
            name='TipoTransacciones',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
