# Generated by Django 5.2.6 on 2025-09-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipocliente_delete_bitacoraventas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocliente',
            options={'managed': False},
        ),
    ]
